@BookManagement_Backend_HostAddress = http://localhost:5145

GET {{BookManagement_Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BookManagement_Backend_HostAddress}}/api/Book/

###

GET {{BookManagement_Backend_HostAddress}}/api/Book/getBooks?formType=Reactive%20Form

}